// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function scuttlebug_geo_define() {
	Object1.scuttlebug_geo = [
   [GCMD_SHADOW, SHADOW_CIRCLE_PLAYER, 0x96, 100],
	   [GCMD_OPEN],
	      [GCMD_SCALE, 0x00, 16384],
	      [GCMD_OPEN],
	         [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	         [GCMD_OPEN],
	            [GCMD_ANIM, LAYER_OPAQUE, 0, -29, 0, null],
	            [GCMD_OPEN],
	               [GCMD_ANIM, LAYER_OPAQUE, -1, 113, 112, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, 198, 0, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 195, 0, 0, null],
	                        [GCMD_OPEN],
	                           [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014378],
	                        [GCMD_CLOSE],
	                        [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014270],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014188],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, -1, 109, -116, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, 198, 0, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 195, 0, 0, null],
	                        [GCMD_OPEN],
	                           [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014378],
	                        [GCMD_CLOSE],
	                        [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014270],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014188],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	               [GCMD_OPEN],
	                  [GCMD_BILLBOARD],
	                  [GCMD_OPEN],
	                     [GCMD_DLIST, LAYER_ALPHA, scuttlebug_seg6_dl_060139F8],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, -29, -57, 28, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, 158, 0, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                        [GCMD_OPEN],
	                           [GCMD_BILLBOARD],
	                           [GCMD_OPEN],
	                              [GCMD_DLIST, LAYER_ALPHA, scuttlebug_seg6_dl_06013AE8],
	                           [GCMD_CLOSE],
	                        [GCMD_CLOSE],
	                        [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06013CB8],
	                     [GCMD_CLOSE],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, -29, 55, 28, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, 157, 0, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                        [GCMD_OPEN],
	                           [GCMD_BILLBOARD],
	                           [GCMD_OPEN],
	                              [GCMD_DLIST, LAYER_ALPHA, scuttlebug_seg6_dl_06013BD0],
	                           [GCMD_CLOSE],
	                        [GCMD_CLOSE],
	                        [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06013DA0],
	                     [GCMD_CLOSE],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, -1, -116, -111, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, 198, 0, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 195, 0, 0, null],
	                        [GCMD_OPEN],
	                           [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014378],
	                        [GCMD_CLOSE],
	                        [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014270],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014188],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, -1, -116, 112, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, 195, 0, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 199, 0, 0, null],
	                        [GCMD_OPEN],
	                           [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014378],
	                        [GCMD_CLOSE],
	                        [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014270],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, scuttlebug_seg6_dl_06014188],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, scuttlebug_seg6_dl_060140F0],
	            [GCMD_CLOSE],
	         [GCMD_CLOSE],
	      [GCMD_CLOSE],
	   [GCMD_CLOSE],
	   [GCMD_END]
   ];
}