// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function door_geo_define(){
	
door_seg3_collision_0301CE78 = [
    COL_INIT(),
    COL_VERTEX_INIT(0x8),
    COL_VERTEX(-80, 240, 30),
    COL_VERTEX(80, 240, 30),
    COL_VERTEX(80, 0, 30),
    COL_VERTEX(-80, 0, 30),
    COL_VERTEX(-80, 240, -30),
    COL_VERTEX(80, 0, -30),
    COL_VERTEX(80, 240, -30),
    COL_VERTEX(-80, 0, -30),

    COL_TRI_INIT(SURFACE_DEFAULT, 4),
    COL_TRI(2, 1, 0),
    COL_TRI(3, 2, 0),
    COL_TRI(6, 5, 4),
    COL_TRI(5, 7, 4),
    COL_TRI_STOP(),
    COL_END(),
];

/// <pygml?v=1.0&h=a58265892>
// 0x160003A8
castle_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014100],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x1600043C
cabin_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013EA8],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014128],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x160004D0
wooden_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014A80],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014F98],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x16000564
wooden_door2_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014B30],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03015008],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x160005F8
metal_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014BE0],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03015078],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x1600068C
hazy_maze_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014C90],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_030150E8],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x16000720
haunted_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 3500],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03014D40],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 3500, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03015158],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x160007B4
castle_door_0_star_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 1000],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_TRANSPARENT, door_seg3_dl_03014250],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 1000, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_TRANSPARENT_DECAL, door_seg3_dl_03014280],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x16000868
castle_door_1_star_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 1000],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_TRANSPARENT, door_seg3_dl_030142B0],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 1000, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_TRANSPARENT_DECAL, door_seg3_dl_030142E0],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x1600091C
castle_door_3_stars_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 1000],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_TRANSPARENT, door_seg3_dl_03014310],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 1000, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_TRANSPARENT_DECAL, door_seg3_dl_03014340],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

// 0x160009D0
key_door_geo = gList(
   [GCMD_TRANSLATE_NODE, 0x00, 78, 0, 0],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, -300, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_OPEN],
               [GCMD_RENDER_RANGE, -2048, 1000],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_OPAQUE, door_seg3_dl_03014540],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_RENDER_RANGE, 1000, 32767],
               [GCMD_OPEN],
                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, door_seg3_dl_03013E28],
                  [GCMD_OPEN],
                     [GCMD_DLIST, LAYER_OPAQUE_DECAL, door_seg3_dl_03014528],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
[GCMD_CLOSE], //! more close than open nodes
[GCMD_END],
);

}