// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function actor_whomp_geo_define(){
// 0x06020A0C - 0x06020A90
whomp_seg6_collision_06020A0C = [
    COL_INIT(),
    COL_VERTEX_INIT(0x8),
    COL_VERTEX(-150, 50, -100),
    COL_VERTEX(150, 50, -100),
    COL_VERTEX(150, 430, -100),
    COL_VERTEX(-150, 430, -100),
    COL_VERTEX(-150, 50, -3),
    COL_VERTEX(150, 430, -3),
    COL_VERTEX(150, 50, -3),
    COL_VERTEX(-150, 430, -3),

    COL_TRI_INIT(SURFACE_NO_CAM_COLLISION, 12),
    COL_TRI(2, 1, 0),
    COL_TRI(3, 2, 0),
    COL_TRI(6, 5, 4),
    COL_TRI(5, 7, 4),
    COL_TRI(7, 5, 3),
    COL_TRI(5, 2, 3),
    COL_TRI(6, 4, 0),
    COL_TRI(1, 6, 0),
    COL_TRI(5, 1, 2),
    COL_TRI(6, 1, 5),
    COL_TRI(0, 7, 3),
    COL_TRI(0, 4, 7),
    COL_TRI_STOP(),
    COL_END(),
];
	/// <pygml?v=1.0&h=61b7c9bc3>
	// 0x0D000480
	whomp_geo = [
	   [GCMD_CULL, 2000],
	   [GCMD_OPEN],
	      [GCMD_TRANSLATE_NODE, 0x00, 0, 0, -50],
	      [GCMD_OPEN],
	         [GCMD_SHADOW, 0x01 + SHADOW_RECTANGLE_HARDCODED_OFFSET, 0xB4, 0],
	         [GCMD_OPEN],
	            [GCMD_SCALE, 0x00, 16384],
	            [GCMD_OPEN],
	               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
	               [GCMD_OPEN],
	                  [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, whomp_seg6_dl_0601F5E0],
	                  [GCMD_OPEN],
	                     [GCMD_ANIM, LAYER_OPAQUE, -12, 490, -5, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, whomp_seg6_dl_0601FEA8],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_OPAQUE, -18, -479, -5, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, whomp_seg6_dl_06020038],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_OPAQUE, 1075, 570, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, whomp_seg6_dl_0601F880],
	                        [GCMD_OPEN],
	                           [GCMD_ANIM, LAYER_ALPHA, 400, 0, 0, null],
	                           [GCMD_OPEN],
	                              [GCMD_BILLBOARD],
	                              [GCMD_OPEN],
	                                 [GCMD_DLIST, LAYER_ALPHA, whomp_seg6_dl_0601FBC0],
	                              [GCMD_CLOSE],
	                           [GCMD_CLOSE],
	                        [GCMD_CLOSE],
	                     [GCMD_CLOSE],
	                     [GCMD_ANIM, LAYER_OPAQUE, 1068, -574, 0, null],
	                     [GCMD_OPEN],
	                        [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, whomp_seg6_dl_0601FAE8],
	                        [GCMD_OPEN],
	                           [GCMD_ANIM, LAYER_ALPHA, 400, 0, 0, null],
	                           [GCMD_OPEN],
	                              [GCMD_BILLBOARD],
	                              [GCMD_OPEN],
	                                 [GCMD_DLIST, LAYER_ALPHA, whomp_seg6_dl_0601FCA8],
	                              [GCMD_CLOSE],
	                           [GCMD_CLOSE],
	                        [GCMD_CLOSE],
	                     [GCMD_CLOSE],
	                  [GCMD_CLOSE],
	               [GCMD_CLOSE],
	            [GCMD_CLOSE],
	         [GCMD_CLOSE],
	      [GCMD_CLOSE],
	   [GCMD_CLOSE],
	   [GCMD_END],
	];

}