function ccm_geo2_define(){
/// <pygml?v=1.0&h=64f3379a7>
ccm_geo_0005E8 = gList(
   [GCMD_SCREEN, 10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2],
   [GCMD_OPEN],
      [GCMD_ZBUFFER, 0],
      [GCMD_OPEN],
         [GCMD_ORTHO, 100],
         [GCMD_OPEN],
            [GCMD_BACKGROUND_COLOR, 0x0001],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
      [GCMD_ZBUFFER, 1],
      [GCMD_OPEN],
         [GCMD_PERSP, 45, 100, 12800, geo_camera_fov],
         [GCMD_OPEN],
            [GCMD_CAMERA, 9, 0, 2000, 6000, 0, 0, 0, geo_camera_main],
            [GCMD_OPEN],
               [GCMD_DLIST, LAYER_OPAQUE, ccm_seg7_dl_0701CE30],
               [GCMD_DLIST, LAYER_OPAQUE, ccm_seg7_dl_0701E558],
               [GCMD_DLIST, LAYER_OPAQUE_DECAL, ccm_seg7_dl_0701E6B0],
               [GCMD_DLIST, LAYER_ALPHA, ccm_seg7_dl_0701FC78],
               [GCMD_DLIST, LAYER_ALPHA, ccm_seg7_dl_0701FD78],
               [GCMD_DLIST, LAYER_TRANSPARENT, ccm_seg7_dl_0701FE60],
               [GCMD_DLIST, LAYER_TRANSPARENT, ccm_seg7_dl_070207F0],
               [GCMD_PARENT],
               //[GCMD_ASM, 0, geo_envfx_main],
            [GCMD_CLOSE],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
   [GCMD_END],
);

}