// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function actor_amp_geo_define(){
/// <pygml?v=1.0&h=b5f7e162d>
// 0x0F000028
amp_geo = gList(
   [GCMD_SHADOW, SHADOW_CIRCLE_4_VERTS, 0xC8, 100],
   [GCMD_OPEN],
      [GCMD_SCALE, 0x00, 16384],
      [GCMD_OPEN],
         [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
         [GCMD_OPEN],
            [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, amp_seg8_dl_08002C88],
            [GCMD_OPEN],
               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
               [GCMD_OPEN],
                  [GCMD_SWITCH, 2, geo_switch_anim_state],
                  [GCMD_OPEN],
                     [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, amp_seg8_dl_08002BA0],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
               [GCMD_OPEN],
                  [GCMD_SWITCH, 2, geo_switch_anim_state],
                  [GCMD_OPEN],
                     [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, amp_seg8_dl_08002BA0],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
               [GCMD_OPEN],
                  [GCMD_SWITCH, 2, geo_switch_anim_state],
                  [GCMD_OPEN],
                     [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, amp_seg8_dl_08002BA0],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
               [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
               [GCMD_OPEN],
                  [GCMD_SWITCH, 2, geo_switch_anim_state],
                  [GCMD_OPEN],
                     [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
                     [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, amp_seg8_dl_08002BA0],
                  [GCMD_CLOSE],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
            [GCMD_ANIM, LAYER_ALPHA, 0, 0, 0, amp_seg8_dl_08002D70],
            [GCMD_ANIM, LAYER_OPAQUE, 0, 0, 0, null],
            [GCMD_OPEN],
               [GCMD_BILLBOARD],
               [GCMD_OPEN],
                  [GCMD_DLIST, LAYER_ALPHA, amp_seg8_dl_08002E58],
               [GCMD_CLOSE],
            [GCMD_CLOSE],
         [GCMD_CLOSE],
      [GCMD_CLOSE],
   [GCMD_CLOSE],
   [GCMD_END],
);


}